// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mtgcard.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetMTGCardParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMTGCardParams) Reset()         { *m = GetMTGCardParams{} }
func (m *GetMTGCardParams) String() string { return proto.CompactTextString(m) }
func (*GetMTGCardParams) ProtoMessage()    {}
func (*GetMTGCardParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_708406b82c21cf0e, []int{0}
}

func (m *GetMTGCardParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMTGCardParams.Unmarshal(m, b)
}
func (m *GetMTGCardParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMTGCardParams.Marshal(b, m, deterministic)
}
func (m *GetMTGCardParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMTGCardParams.Merge(m, src)
}
func (m *GetMTGCardParams) XXX_Size() int {
	return xxx_messageInfo_GetMTGCardParams.Size(m)
}
func (m *GetMTGCardParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMTGCardParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetMTGCardParams proto.InternalMessageInfo

type AddMTGCardParams struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Qty                  int32    `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMTGCardParams) Reset()         { *m = AddMTGCardParams{} }
func (m *AddMTGCardParams) String() string { return proto.CompactTextString(m) }
func (*AddMTGCardParams) ProtoMessage()    {}
func (*AddMTGCardParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_708406b82c21cf0e, []int{1}
}

func (m *AddMTGCardParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMTGCardParams.Unmarshal(m, b)
}
func (m *AddMTGCardParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMTGCardParams.Marshal(b, m, deterministic)
}
func (m *AddMTGCardParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMTGCardParams.Merge(m, src)
}
func (m *AddMTGCardParams) XXX_Size() int {
	return xxx_messageInfo_AddMTGCardParams.Size(m)
}
func (m *AddMTGCardParams) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMTGCardParams.DiscardUnknown(m)
}

var xxx_messageInfo_AddMTGCardParams proto.InternalMessageInfo

func (m *AddMTGCardParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddMTGCardParams) GetQty() int32 {
	if m != nil {
		return m.Qty
	}
	return 0
}

type DeleteMTGCardParams struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Qty                  int32    `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMTGCardParams) Reset()         { *m = DeleteMTGCardParams{} }
func (m *DeleteMTGCardParams) String() string { return proto.CompactTextString(m) }
func (*DeleteMTGCardParams) ProtoMessage()    {}
func (*DeleteMTGCardParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_708406b82c21cf0e, []int{2}
}

func (m *DeleteMTGCardParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMTGCardParams.Unmarshal(m, b)
}
func (m *DeleteMTGCardParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMTGCardParams.Marshal(b, m, deterministic)
}
func (m *DeleteMTGCardParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMTGCardParams.Merge(m, src)
}
func (m *DeleteMTGCardParams) XXX_Size() int {
	return xxx_messageInfo_DeleteMTGCardParams.Size(m)
}
func (m *DeleteMTGCardParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMTGCardParams.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMTGCardParams proto.InternalMessageInfo

func (m *DeleteMTGCardParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteMTGCardParams) GetQty() int32 {
	if m != nil {
		return m.Qty
	}
	return 0
}

type MTGCard struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Qty                  int32    `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MTGCard) Reset()         { *m = MTGCard{} }
func (m *MTGCard) String() string { return proto.CompactTextString(m) }
func (*MTGCard) ProtoMessage()    {}
func (*MTGCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_708406b82c21cf0e, []int{3}
}

func (m *MTGCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MTGCard.Unmarshal(m, b)
}
func (m *MTGCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MTGCard.Marshal(b, m, deterministic)
}
func (m *MTGCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MTGCard.Merge(m, src)
}
func (m *MTGCard) XXX_Size() int {
	return xxx_messageInfo_MTGCard.Size(m)
}
func (m *MTGCard) XXX_DiscardUnknown() {
	xxx_messageInfo_MTGCard.DiscardUnknown(m)
}

var xxx_messageInfo_MTGCard proto.InternalMessageInfo

func (m *MTGCard) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MTGCard) GetQty() int32 {
	if m != nil {
		return m.Qty
	}
	return 0
}

type MTGCardResponse struct {
	Cards                []*MTGCard `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MTGCardResponse) Reset()         { *m = MTGCardResponse{} }
func (m *MTGCardResponse) String() string { return proto.CompactTextString(m) }
func (*MTGCardResponse) ProtoMessage()    {}
func (*MTGCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_708406b82c21cf0e, []int{4}
}

func (m *MTGCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MTGCardResponse.Unmarshal(m, b)
}
func (m *MTGCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MTGCardResponse.Marshal(b, m, deterministic)
}
func (m *MTGCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MTGCardResponse.Merge(m, src)
}
func (m *MTGCardResponse) XXX_Size() int {
	return xxx_messageInfo_MTGCardResponse.Size(m)
}
func (m *MTGCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MTGCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MTGCardResponse proto.InternalMessageInfo

func (m *MTGCardResponse) GetCards() []*MTGCard {
	if m != nil {
		return m.Cards
	}
	return nil
}

type DeleteResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_708406b82c21cf0e, []int{5}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetMTGCardParams)(nil), "api.getMTGCardParams")
	proto.RegisterType((*AddMTGCardParams)(nil), "api.addMTGCardParams")
	proto.RegisterType((*DeleteMTGCardParams)(nil), "api.deleteMTGCardParams")
	proto.RegisterType((*MTGCard)(nil), "api.MTGCard")
	proto.RegisterType((*MTGCardResponse)(nil), "api.MTGCardResponse")
	proto.RegisterType((*DeleteResponse)(nil), "api.deleteResponse")
}

func init() { proto.RegisterFile("mtgcard.proto", fileDescriptor_708406b82c21cf0e) }

var fileDescriptor_708406b82c21cf0e = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x26, 0xad, 0xb5, 0x38, 0xda, 0x1f, 0xa6, 0xad, 0x84, 0xd2, 0x43, 0xd9, 0x53, 0xe9, 0xa1,
	0xc1, 0x8a, 0x20, 0x7a, 0x12, 0x85, 0x9e, 0x84, 0xd2, 0x7a, 0xf4, 0x32, 0x36, 0x43, 0x08, 0x34,
	0xbb, 0x31, 0xbb, 0x14, 0x8a, 0x78, 0xf1, 0x15, 0xc4, 0x27, 0xf3, 0x15, 0x7c, 0x10, 0xe9, 0x36,
	0x09, 0x4d, 0x51, 0x10, 0x6f, 0xb3, 0x3b, 0xf3, 0xfd, 0xec, 0x37, 0x0b, 0xb5, 0xc8, 0x04, 0x0b,
	0x4a, 0xfc, 0x51, 0x9c, 0x28, 0xa3, 0xb0, 0x4c, 0x71, 0xd8, 0xed, 0x05, 0x4a, 0x05, 0x4b, 0xf6,
	0x28, 0x0e, 0x3d, 0x92, 0x52, 0x19, 0x32, 0xa1, 0x92, 0x7a, 0x3b, 0x22, 0x10, 0x9a, 0x01, 0x9b,
	0xfb, 0x87, 0xc9, 0x2d, 0x25, 0xfe, 0x94, 0x12, 0x8a, 0xb4, 0xb8, 0x84, 0x26, 0xf9, 0x7e, 0xe1,
	0x0e, 0x11, 0x0e, 0x24, 0x45, 0xec, 0x3a, 0x7d, 0x67, 0x70, 0x34, 0xb3, 0x35, 0x36, 0xa1, 0xfc,
	0x6c, 0xd6, 0x6e, 0xa9, 0xef, 0x0c, 0x2a, 0xb3, 0x4d, 0x29, 0xae, 0xa1, 0xe5, 0xf3, 0x92, 0x0d,
	0xff, 0x07, 0xec, 0x41, 0x35, 0x85, 0xfd, 0x11, 0x70, 0x01, 0x8d, 0x14, 0x30, 0x63, 0x1d, 0x2b,
	0xa9, 0x19, 0x05, 0x54, 0x36, 0xef, 0xd7, 0xae, 0xd3, 0x2f, 0x0f, 0x8e, 0xc7, 0x27, 0x23, 0x8a,
	0xc3, 0x51, 0x36, 0xb4, 0x6d, 0x89, 0x21, 0xd4, 0xb7, 0x26, 0x73, 0x94, 0x0b, 0xd5, 0x88, 0xb5,
	0xa6, 0x20, 0x53, 0xcc, 0x8e, 0xe3, 0x8f, 0x12, 0xd4, 0x53, 0xf8, 0x9c, 0x93, 0x55, 0xb8, 0x60,
	0x9c, 0x03, 0xdc, 0xe4, 0xe9, 0x60, 0xc7, 0x2a, 0xec, 0xc7, 0xd5, 0x6d, 0x17, 0x84, 0x53, 0x1d,
	0xe1, 0xbe, 0x7d, 0x7e, 0xbd, 0x97, 0x50, 0xd4, 0xbc, 0xd5, 0x99, 0x17, 0xca, 0x15, 0x4b, 0xa3,
	0x92, 0xf5, 0x95, 0x33, 0xc4, 0x47, 0xa8, 0xdd, 0xed, 0x06, 0x87, 0xae, 0x25, 0xf8, 0x21, 0xcc,
	0x6e, 0x6b, 0xa7, 0x93, 0x33, 0xf7, 0x2c, 0xf3, 0xe9, 0xb0, 0x5d, 0x60, 0xf6, 0x5e, 0x36, 0xc9,
	0xbd, 0xe2, 0x14, 0x60, 0x92, 0x2f, 0x39, 0xb5, 0xbc, 0xbf, 0xf5, 0x5f, 0x2c, 0x77, 0x2c, 0x71,
	0x03, 0x8b, 0x96, 0x9f, 0x0e, 0xed, 0xef, 0x39, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x95,
	0x8b, 0x46, 0x71, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MTGCardServiceClient is the client API for MTGCardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MTGCardServiceClient interface {
	AddMTGCard(ctx context.Context, in *AddMTGCardParams, opts ...grpc.CallOption) (*MTGCardResponse, error)
	DeleteMTGCard(ctx context.Context, in *DeleteMTGCardParams, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetMTGCard(ctx context.Context, in *GetMTGCardParams, opts ...grpc.CallOption) (*MTGCardResponse, error)
}

type mTGCardServiceClient struct {
	cc *grpc.ClientConn
}

func NewMTGCardServiceClient(cc *grpc.ClientConn) MTGCardServiceClient {
	return &mTGCardServiceClient{cc}
}

func (c *mTGCardServiceClient) AddMTGCard(ctx context.Context, in *AddMTGCardParams, opts ...grpc.CallOption) (*MTGCardResponse, error) {
	out := new(MTGCardResponse)
	err := c.cc.Invoke(ctx, "/api.MTGCardService/AddMTGCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTGCardServiceClient) DeleteMTGCard(ctx context.Context, in *DeleteMTGCardParams, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/api.MTGCardService/DeleteMTGCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTGCardServiceClient) GetMTGCard(ctx context.Context, in *GetMTGCardParams, opts ...grpc.CallOption) (*MTGCardResponse, error) {
	out := new(MTGCardResponse)
	err := c.cc.Invoke(ctx, "/api.MTGCardService/GetMTGCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MTGCardServiceServer is the server API for MTGCardService service.
type MTGCardServiceServer interface {
	AddMTGCard(context.Context, *AddMTGCardParams) (*MTGCardResponse, error)
	DeleteMTGCard(context.Context, *DeleteMTGCardParams) (*DeleteResponse, error)
	GetMTGCard(context.Context, *GetMTGCardParams) (*MTGCardResponse, error)
}

// UnimplementedMTGCardServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMTGCardServiceServer struct {
}

func (*UnimplementedMTGCardServiceServer) AddMTGCard(ctx context.Context, req *AddMTGCardParams) (*MTGCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMTGCard not implemented")
}
func (*UnimplementedMTGCardServiceServer) DeleteMTGCard(ctx context.Context, req *DeleteMTGCardParams) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMTGCard not implemented")
}
func (*UnimplementedMTGCardServiceServer) GetMTGCard(ctx context.Context, req *GetMTGCardParams) (*MTGCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMTGCard not implemented")
}

func RegisterMTGCardServiceServer(s *grpc.Server, srv MTGCardServiceServer) {
	s.RegisterService(&_MTGCardService_serviceDesc, srv)
}

func _MTGCardService_AddMTGCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMTGCardParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTGCardServiceServer).AddMTGCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MTGCardService/AddMTGCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTGCardServiceServer).AddMTGCard(ctx, req.(*AddMTGCardParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTGCardService_DeleteMTGCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMTGCardParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTGCardServiceServer).DeleteMTGCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MTGCardService/DeleteMTGCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTGCardServiceServer).DeleteMTGCard(ctx, req.(*DeleteMTGCardParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTGCardService_GetMTGCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMTGCardParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTGCardServiceServer).GetMTGCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MTGCardService/GetMTGCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTGCardServiceServer).GetMTGCard(ctx, req.(*GetMTGCardParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _MTGCardService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MTGCardService",
	HandlerType: (*MTGCardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMTGCard",
			Handler:    _MTGCardService_AddMTGCard_Handler,
		},
		{
			MethodName: "DeleteMTGCard",
			Handler:    _MTGCardService_DeleteMTGCard_Handler,
		},
		{
			MethodName: "GetMTGCard",
			Handler:    _MTGCardService_GetMTGCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mtgcard.proto",
}
